const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Signs Android release builds with the SplitMoney upload key.
 *
 * `android/` is regenerated by `expo prebuild --clean`, so the signing setup has to live
 * here rather than in a hand-edited build.gradle. The template signs release builds with
 * the DEBUG key, which Play rejects; this replaces that.
 *
 * NO SECRETS IN THE REPOSITORY. The keystore path, alias and both passwords are read at
 * build time from Gradle properties or environment variables:
 *
 *   SPLITMONEY_UPLOAD_STORE_FILE      path to the .jks (default: app/splitmoney-release.jks)
 *   SPLITMONEY_UPLOAD_KEY_ALIAS
 *   SPLITMONEY_UPLOAD_STORE_PASSWORD
 *   SPLITMONEY_UPLOAD_KEY_PASSWORD
 *
 * Set them in ~/.gradle/gradle.properties, as environment variables, or let
 * scripts/build-android-release.ps1 prompt for them. Without them the release build is
 * produced UNSIGNED and says so — it never falls back to the debug key.
 */
const MARKER = '// splitmoney-release-signing';

const SIGNING = `
    ${MARKER}
    def smProp = { String name -> (project.findProperty(name) ?: System.getenv(name))?.toString()?.trim() }
    def smStoreFile = smProp('SPLITMONEY_UPLOAD_STORE_FILE') ?: new File(rootDir, '../splitmoney-release.jks').canonicalPath
    def smReady = smProp('SPLITMONEY_UPLOAD_KEY_ALIAS') && smProp('SPLITMONEY_UPLOAD_STORE_PASSWORD') && smProp('SPLITMONEY_UPLOAD_KEY_PASSWORD') && new File(smStoreFile).exists()
    if (smReady) {
        signingConfigs {
            splitmoneyUpload {
                storeFile new File(smStoreFile)
                storePassword smProp('SPLITMONEY_UPLOAD_STORE_PASSWORD')
                keyAlias smProp('SPLITMONEY_UPLOAD_KEY_ALIAS')
                keyPassword smProp('SPLITMONEY_UPLOAD_KEY_PASSWORD')
            }
        }
    } else {
        logger.warn('SplitMoney: upload key not configured - the release build will be UNSIGNED. See app/BUILD.md.')
    }
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    let gradle = mod.modResults.contents;
    if (gradle.includes(MARKER)) return mod;

    // Declare the upload key just before buildTypes.
    gradle = gradle.replace(/(\n\s*buildTypes\s*\{)/, `${SIGNING}$1`);

    // In the release block only: upload key when configured, otherwise unsigned.
    gradle = gradle.replace(
      /(release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
      '$1signingConfig smReady ? signingConfigs.splitmoneyUpload : null',
    );

    if (!gradle.includes('signingConfigs.splitmoneyUpload')) {
      throw new Error('withReleaseSigning: could not find the release signingConfig in app/build.gradle');
    }
    mod.modResults.contents = gradle;
    return mod;
  });
};
